/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nam' at '24/02/17 3:31 PM' with Gradle 3.1
 *
 * @author nam, @date 24/02/17 3:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
