/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'nick_000' at '8/11/16 3:25 PM' with Gradle 3.0
 *
 * @author nick_000, @date 8/11/16 3:25 PM
 */

import gov.au.dva.sopapi.{JavaTest, ScalaTest}
import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("scala method executes") {
     def library = new ScalaTest()
    assert(library.returnsTrue())
  }

  test("java method executes") {
    assert(JavaTest.returnsTrue())
  }
}


