swagger: "2.0"

info:
  version: 1.0.0
  title: DVA-SOP-API
  description: An API providing information about Statements of Principles (SOP) and Veteran Centric Processing for the Department of Veterans' Affairs (Australia).

schemes:
  - http
  - https
# If host isn't specified, the UI defaults to the current host - which is probably what we want
#host: where.is.this.hosted.com?
basePath: /

paths:
  /getOperations:
    get:
      summary: Gets all the configured operations
      description: Returns a list containing a description of every valid operation.
      tags:
        - dva-sop-api
      responses:
        200:
          description: Successfully found operations
          schema:
            $ref: "#/definitions/OperationsResponse"
        406:
          description: The client was unable to accept a JSON response

  /getSopFactors:
    get:
      summary: Gets a list of SoP factors
      description: Returns a list SoP Factors, that match a particular condition, incident type and standard of proof. The request should contain either an icdCode value and icdVersion, or a text Condition name
      tags:
        - dva-sop-api
      parameters:
        - name: icdCodeValue
          in: query
          description: ICD Code Value
          type: string
        - name: icdCodeVersion
          in: query
          description: ICD Code Version
          type: string
        - name: standardOfProof
          in: query
          description: Standard of Proof
          type: string
          enum:
            - RH
            - BoP
        - name: conditionName
          in: query
          description: Condition Name
          type: string
        - name: incidentType
          in: query
          description: Incident Type
          type: string
          enum:
            - aggravation
            - onset
      responses:
        200:
          description: Successfully found SoP Factors
          schema:
            $ref: "#/definitions/SoPReferenceResponse"
        400:
          description: The provided query parameters make for a malformed request
        404:
          description: No matching SoPs were found for the provided query parameters
        406:
          description: The client was unable to accept a JSON response

  /getConnectionToService:
    post:
      summary: Gets the applicable instrument and satisfied factors associated with a condition and service history
      description: Gets the applicable instrument and satisfied factors associated with a condition and service history. This is used to make Veteran Centric Processing recommendations.
      tags:
        - dva-sop-api
      parameters:
        - name: supportRequest
          in: body
          description: Support request JSON
          schema:
            $ref: "#/definitions/SoPSupportRequest"
      responses:
        200:
          description: Successfully serviced the support request
          schema:
            $ref: "#/definitions/SoPSupportResponse"
        400:
          description: The request body was malformed
        406:
          description: The client was unable to accept a JSON response

definitions:
  OperationsResponse:
    required:
      - registerIds
      - operations
    properties:
      registerIds:
        type: array
        items:
          type: string
      operations:
        type: array
        items:
          $ref: "#/definitions/Operation"
  Operation:
    required:
      - operationName
      - startDate
      - type
    properties:
      operationName:
        type: string
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
      type:
        type: string
  SoPReferenceResponse:
    required:
      - applicableFactors
    properties:
      applicableFactors:
        type: array
        items:
          $ref: "#/definitions/SoPFactorsResponse"
  SoPFactorsResponse:
    required:
      - registerId
      - citation
      - instrumentNumber
      - factors
    properties:
      registerId:
        type: string
      citation:
        type: string
      instrumentNumber:
        type: string
      factors:
        type: array
        items:
          $ref: "#/definitions/Factor"
  Factor:
    required:
      - paragraph
      - text
      - definedTerms
    properties:
      paragraph:
        type: string
      text:
        type: string
      definedTerms:
        type: array
        items:
          $ref: "#/definitions/DefinedTerm"
  DefinedTerm:
    required:
      - term
      - definition
    properties:
      term:
        type: string
      definition:
        type: string
  SoPSupportRequest:
    required:
      - condition
      - serviceHistory
    properties:
      condition:
        $ref: "#/definitions/Condition"
      serviceHistory:
        $ref: "#/definitions/ServiceHistory"
  Condition:
    required:
      - conditionName
      - incidentType
    properties:
      conditionName:
        type: string
      incidentType:
        $ref: "#/definitions/IncidentType"
      icdCodeVersion:
        type: string
      icdCodeValue:
        type: string
      onsetDates:
        $ref: "#/definitions/OnsetDateRange"
      aggravationDates:
        $ref: "#/definitions/AggravationDateRange"
  IncidentType:
    type: string
    enum:
      - onset
      - aggravation
  OnsetDateRange:
    required:
      - onsetRangeStartDate
      - onsetRangeEndDate
    properties:
      onsetRangeStartDate:
        type: string
        format: date
      onsetRangeEndDate:
        type: string
        format: date
  AggravationDateRange:
    required:
      - aggravationRangeStartDate
      - aggravationRangeEndDate
    properties:
      aggravationRangeStartDate:
        type: string
        format: date
      aggravationRangeEndDate:
        type: string
        format: date
  ServiceHistory:
    required:
      - serviceSummaryInformation
      - serviceDetails
    properties:
      serviceSummaryInformation:
        $ref: '#/definitions/ServiceSummaryInfo'
      serviceDetails:
        type: array
        items:
          $ref: '#/definitions/Service'
  ServiceSummaryInfo:
    required:
      - originalHireDate
    properties:
      originalHireDate:
        type: string
        format: date
  Service:
    required:
      - service
      - serviceType
      - startDate
      - endDate
      - rank
      - operationalService
    properties:
      service:
        $ref: '#/definitions/ServiceBranch'
      serviceType:
        $ref: '#/definitions/EmploymentType'
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
      rank:
        $ref: '#/definitions/Rank'
      operationalService:
        type: array
        items:
          $ref: '#/definitions/OperationalService'
  ServiceBranch:
    type: string
    enum:
      - Australian Army
      - Royal Australian Navy
      - Royal Australian Air Force
  EmploymentType:
    type: string
    enum:
      - Regular/Permanent Force
      - Non-Regular/Permanent Force
  Rank:
    type: string
    enum:
      - officer
      - other rank
      - special forces
  OperationalService:
    required:
      - description
      - event
      - startDate
    properties:
      assigned:
        type: string
        format: date
      description:
        type: string
      event:
        type: string
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
  SoPSupportResponse:
    required:
      - applicableInstrument
      - factors
      - recommendation
      - caseTrace
    properties:
      applicableInstrument:
        $ref: "#/definitions/ApplicableInstrument"
      factors:
        type: array
        items:
          $ref: "#/definitions/FactorWithInferredResultDto"
      recommendation:
        type: string
        enum:
        - Accept claim
        - Review claim details
        - Review operational service to check all factors, otherwise accept as BoP factor met
        - Review operational service to check all factors
      caseTrace:
        $ref: "#/definitions/CaseTraceDto"
  ApplicableInstrument:
    required:
      - registerId
      - instrumentNumber
      - citation
      - effectiveFromDate
      - standardOfProof
    properties:
      registerId:
        type: string
      instrumentNumber:
        type: string
      citation:
        type: string
      effectiveFromDate:
        type: string
        format: date
      standardOfProof:
        type: string
        enum:
          - Reasonable Hypothesis
          - Balance of Probabilities
  FactorWithInferredResultDto:
    required:
      - paragraph
      - text
      - definedTerms
      - satisfied
    properties:
      paragraph:
        type: string
      text:
        type: string
      definedTerms:
        type: array
        items:
          $ref: "#/definitions/DefinedTerm"
      satisfied:
        type: boolean
  CaseTraceDto:
    required:
      - rhFactors
      - bopFactors
      - reasonings
      - logTrace
    properties:
      standardOfProof:
        type: string
        enum:
          - Reasonable Hypothesis
          - Balance of Probabilities
      requiredDaysOfCfts:
        type: integer
      requiredDaysOfCftsForRh:
        type: integer
      requiredDaysOfCftsForBop:
        type: integer
      actualDaysOfCfts:
        type: integer
      requiredDaysOfOperationalServiceForRhStandard:
        type: integer
      actualDaysOfOperationalServiceInTestPeriod:
        type: integer
      rhFactors:
        type: array
        items:
          $ref: "#/definitions/Factor"
      bopFactors:
        type: array
        items:
          $ref: "#/definitions/Factor"
      reasonings:
        $ref: "#/definitions/ReasoningMap"
      logTrace:
        type: string
  ReasoningMap:
    properties:
      ABORT_PROCESSING:
        type: array
        items:
          type: string
      STANDARD_OF_PROOF:
        type: array
        items:
          type: string
      MEETING_FACTORS:
        type: array
        items:
          type: string

