/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nick_000' at '15/12/16 4:17 PM' with Gradle 3.0
 *
 * @author nick_000, @date 15/12/16 4:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
